# Numpy 개요

## ndarray


In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('aaray1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array 형태:', array3.shape)


array1 type: <class 'numpy.ndarray'>
aaray1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array 형태: (1, 3)


In [5]:
print('array1: {:0}차원, array2:{:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2:2차원, array3:  2차원


In [7]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(array1, array1.dtype)

<class 'list'>
[1 2 3] int64


# 서로 다은 데이터 타입을 Ndarray 같이 쓰기

ndarray는 같은 데이터 타입만 가능하다했지만, 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄적용.
int 형과 string형이 섞여 있는 리스트와 int형과 float형이 섞여 있는 리스트를 ndarray로 변경하면 데이터값의 타입은 어떻게 되는지 확인

int 8bit, 16bit, 32bit
unsinged int 8bit, 16bit, 32bit
float 16bit, 32bit, 64bit, 128bit

In [9]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


list2 1, 2, test 값을 ndarray로 변환한 array2는 숫자형 값 1,2가 모두 문자열 값인 1,2로 변환
이처럼 ndarray는 데이터 값이 모두 같은 데이터 타입이여야 하므로 서로 다른 문자열이 섞여 있을 경우 더 큰 데이터 타입으로 변환되어 int형이 유니코드 문자열 값으로 변환.

따라서, int형과 float형이 섞여 있는 list3의 경우도 int 1,2 가 모두 1.2인 float64형으로 변환



## astype()
ndarray 내 데이터값의 타입 변경도 astype()를 이용해 활용할 수 있음.

사용방법 : astype()에 인자로 원하는 타입을 문자열로 지정하면 됨.

이렇게 데이터 타입을 변경하는 경우는 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되는데, 메모리를 절약해야 할 때 보통 이용됨.
가령 int형으로 충분한 경우인데, 데이터 타입이 float라면 int형으로 바꿔서 메모리를 절약할 수 있음.

### astype 예졔

다음 예제는 int32형 데이터를 float64로 변환하고 다시 float64를 int32로 변경
(float -> int형으로 변경할 때 소수점 이하는 당연히 모두 없어짐)

In [12]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones
 
 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야할 필요가 있음.
 주로 테스트용 데이터를 만들거나, 대규모 데이터를 일괄적으로 초기화해야할 경우
 
 -arange()
 -zero()
 -ones()

## arange()

python의 표준 함수인 range()와 유사한 기능을 함
쉽게 생각하면 array를 arange()로 표현, 0부터 함수 인자 값 -1까지 값을 순차적으로 ndarray의 데이터 값으로 변환

In [13]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


defult 함수 인자는 stip값이며, 0부터 stip값인 10에서 01을 더한 9까지 연속 숫자 값으로 구성된 1차원 ndarray를 만들어줌.
여기서 stop값만 부여했으나 range와 유사하게 start값도 부여해 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수 있음.

## zero()

zeros()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환

## ones()

zeros()와 유사하게 ones() 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환함.
함수 인자로 dtype을 정해주지 않으면 default로 float64 형태로 ndarray를 채움

In [14]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# reshape()

reshape 매서드는 ndarray를 특정 차원 및 크기로 변환.
변환을 원하는 크기를 함수 인자로 부여. 

아래 예제는 0~9까지의 1차원 ndarray를 2row * 5 caloum & 5row * 2 caloum 형태로 2차원 ndarray 변환

reshape() 는 지정된 사이즈로 변경이 불가능하면 오류를 발생함.
가령(10,) 데이터를 (4,3)Shape 형태로 변경할 수 없음

In [20]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
